### ISSUE TITLE
Alternative to batch script

### ISSUE THREAD

**Issue by M4RCK5** [nekoify/counter-strike-source-discord-rpc#1]
U could use "steam://launch/240" to launch CS:S and then make the script wait for the process to end using a loop to check once a min.

**Comment by nekoify** [comment]
You can already use the Steam link if you have cs:s set to run the batch script and the actual program already exits once it doesn't detect the program if that's what you mean. Looking back at this, I could probably move the functionality of the batch script into the actual program and then all you would have to do is change exe cs:s uses which isn't very hard.
